version: '3'
services:
  web_http1:
    image: nginx:latest
    volumes:
      - ./sites/site1:/usr/share/nginx/html
      - ./sites/site1/http1.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "8443:443"
    depends_on:
      - php_http1

  php_http1:
    image: php:fpm
    volumes:
      - ./sites/site1:/var/www/html

  web_http2:
    image: nginx:latest
    volumes:
      - ./sites/site2:/usr/share/nginx/html
      - ./sites/site2/http2.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "8444:443"
    depends_on:
      - php_http2

  php_http2:
    image: php:fpm
    volumes:
      - ./sites/site2:/var/www/html

  web_http3:
    image: caddy:latest
    volumes:
      - ./sites/site3:/usr/share/nginx/html
      - ./sites/site3/Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/caddy/certs
    ports:
      - "8445:443"
      - "8445:443/udp"
    depends_on:
      - php_http3

  php_http3:
    image: php:fpm
    volumes:
      - ./sites/site3:/var/www/html
