version: '3'

services:
  nginx-denial-of-service:
    image: nginx
    volumes:
      - ./nginx-xss.conf:/etc/nginx/nginx.conf
      - ./site-cross-site-scripting:/usr/share/nginx/html
    ports:
      - 8090:80
    links:
      - php15

  php15:
    image: php:fpm
    volumes:
      - ./site-cross-site-scripting:/var/www/html
