version: '3'

services:
  nginx-denial-of-service:
    image: nginx
    volumes:
      - ./nginx-dos.conf:/etc/nginx/nginx.conf
      - ./site-denial-of-service:/usr/share/nginx/html
     # - ./nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt
     # - ./nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key
    ports:
      - 8089:80
    links:
      - php14

  php14:
    image: php:fpm
    volumes:
      - ./site-denial-of-service:/var/www/html
